# Generated by Django 2.1.10 on 2019-10-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20191013_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Liked'), (2, 'Commented')], null=True),
        ),
    ]
