# Generated by Django 2.1.10 on 2019-10-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20191018_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
