# Generated by Django 2.2.6 on 2019-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bkgrd_pic',
            field=models.ImageField(default='', null=True, upload_to='background/'),
        ),
    ]
