# Generated by Django 2.2.6 on 2019-10-07 15:27

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_bkgrd_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=apps.common.utils.get_id_token, editable=False, primary_key=True, serialize=False),
        ),
    ]
