# Generated by Django 2.2.6 on 2019-10-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
