# Generated by Django 2.2.6 on 2019-10-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191014_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name': 'post', 'verbose_name_plural': 'post'},
        ),
    ]
