# Generated by Django 2.2.6 on 2019-10-15 01:31

import apps.account.random_code
import apps.common.uploades
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pic', models.ImageField(blank=True, default='', null=True, upload_to=apps.common.uploades.upload_loc)),
                ('code', models.CharField(blank=True, default=apps.account.random_code.generate_code, max_length=6, null=True)),
                ('bio', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ('-created',),
            },
        ),
    ]
