# Generated by Django 2.2.6 on 2019-10-15 04:55

import apps.common.uploades
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191015_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default=apps.common.uploades.get_default_avatar_url, null=True, upload_to=apps.common.uploades.upload_loc, validators=[apps.common.uploades.validate_uploaded_file_size_and_extension]),
        ),
    ]
