# Generated by Django 2.2.6 on 2019-10-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'NewsLetter', 'verbose_name_plural': "NewsLetter's"},
        ),
    ]
